const clickBtn = document.getElementById('click');
const id = lastId + 1; // lastId - последний id в базе данных
// questions  - русские слова
// answers - английские слова
const newArr = [
    'lump sum', 'единовременно выплачиваемая сумма',
    'dip', 'падать',
    'down the line', 'в дальнейшем /спустя, через',
    'momentum', 'импульс /Движущая сила',
    'outlook', 'перспектива /вид',
    'adverse', 'неблагоприятный /враждебный',
    'tentative', 'предварительный /неопределенный',
    'haul', 'перевозка',
    'impetus', 'импульс',
    'principal', 'капитал',
    'pull the plug', 'прекратить финансирование',
    'flick', 'щелчок /переключатель',
    'through gritted teeth', 'стиснутые зубы',
    'deceit', 'обман',
    'tut', 'щелчок языком',
    'chug', 'пыхтеть /пыхтение',
    'to be divulged', 'быть раскрытым',
    'tangy', 'пряный /острый',
    'gawp', 'пялиться',
    'crunch across the shingle', 'хрустеть по гальке',
    'holiday snaps', 'снимки с отпуска',
    'to fancy someone', 'нравиться кому-то',
    'to be in a huff', 'обижаться',
    'to be in a flap', 'быть в панике',
    'to be in a pickle', 'быть в затруднении',
    'to be in a fix', 'быть в затруднении',
    'to be in a jam', 'быть в затруднении',
    'to be in a muddle /state /tizzy /stew', 'быть в замешательстве',
    'to wail', 'вопить',
    'aloof', 'высокомерный /сноб',
    'gleeful', 'веселый /радостный',
    'to loll', 'висеть /полулежать',
    'brindled (animal)', 'пестрый /полосатый как тигр',
    'lurcher', 'беспородная собака',
    'plimsolls', 'кеды',
    'bramble', 'ежевика',
    'hawthorn', 'боярышник',
    'scowl', 'хмуриться /хмурое лицо',
    'enticing', 'заманчивый',
    'caveat', 'предостережение',
    'mudflats', 'морской пляж /прибрежная отмель',
    'ebb', 'отлив /отступать',
    'freshly-gleaned', 'свежесобранный',
    'to glean', 'собирать /собирать остатки',
    'coarse', 'грубый /крупный',
    'hone', 'точить /точило',
    'sultry-sweet', 'душный /сухой',
    'honeysuckle', 'жимолость',
    'crave', 'жаждать /желать',
    'hem', 'край /кайма',
    'frayed', 'изношенный /потрепанный',
    'thicket', 'чаща /заросли',
    'fell', 'лес /лесной массив /сопка',
    'judder (of wheels against wood)', 'дрожать /дрожание',
    'unpruned', 'неподрезанный',
    'languish', 'мучиться /страдать',
    'owt', 'что-нибудь /anything',
    'shatter', 'разбивать /разрушать',
    'jolt', 'толчок /толчки',
    'drought', 'засуха',
    'draughty', 'сквозняк',
    'entwined', 'сплетенный',
    'bay-window', 'эркерное окно',
    'beckon', 'манить /манящий',
    'cling', 'цепляться /цепляться',
    'despondent', 'унылый /подавленный',
    'slums', 'трущобы',
    'woozy', 'головокружительный',
    'ooze', 'вытекать /вытекание',
    'drivel', 'бред /бредить',
    'adventurous eater', 'любитель экзотической еды',
    'take a toll', 'принести убытки',
    'bleachers', 'трибуны',
    'nick', 'выемка /вырезка',
    'to be in the nick of time', 'вовремя',
    'swing by there', 'заехать туда',
    'go off on somebody for smth.', 'выругаться на кого-то',
    'complacent', 'инертный /самоуспокоенный',
    'to be up for smth.', 'быть готовым к чему-то',
    'to be through the roof', 'быть на пике',
    'infuriating', 'раздражающий',
    'lap pie', 'мак бук',
    'merriment', 'веселье',
    'to be in the mood for smth.', 'быть в настроении для чего-то',
    'to crack somebody up', 'заставить кого-то рассмеяться',
    'a pipe dream', 'мечта',
    'to find their groove', 'найти свой путь',
    'to be in the groove', 'быть в своей тарелке',
    'wedge', 'клин /кусок',
    'police procedurals', 'детективы',
    'psychological twists', 'психологические повороты',
    'true-to-life', 'реалистичный',
    'news anchor', 'ведущий новостей',
    'pop into a pub for some food', 'зайти в паб поесть',
    'barbell', 'штанга',
    'pluck', 'смелость /смелый',
    'can whip up', 'может приготовить на скорую руку',
    'you live and learn', 'человек учится всю жизнь',
    'to be a bit patchy around here at the best of times', 'здесь всегда было не очень',
    'tumbleweed moment', 'момент тишины',
    'to be on the shortlist', 'быть в списке претендентов',
    'smart money says so', 'умные люди так говорят',
    'peddler of sordid lies', 'продавец грязных лжи',
    'redolent', 'напоминающий /пахнущий',
    'swerve', 'резко сворачивать /резкое движение',
    'squalor', 'непристойность /грязь /нищета',
    'coalesced', 'соединенный /объединенный',
    'lump', 'кусок /глыба',
    'fetch', 'принести /приносить',
    'scuffle', 'драка ',
    'ludicrous', 'нелепый /смехотворный',
    'scuttled', 'уничтожать /затоплять /удирать',
    'tumble', 'падать /падение',
    'exasperation', 'раздражение /сердитость',
    'overhang', 'нависать /нависание',
    'topple', 'опрокидывать /опрокидываться',
    'dale', 'долина',
    'forfeiting', 'утрачивать /лишаться',
    'arousal', 'возбуждение /подъем',
    'swoop down', 'набрасываться',
    'appalling', 'ужасный /ужасающий',
    'bereavement', 'потеря /утрата',
    'rustle', 'шелест /шелестеть',
    'acquaintance', 'знакомство /знакомый',
    'to be in the know', 'быть в курсе',
    'devoutly', 'набожно',
    'outrageous', 'возмутительный /непристойный',
    'lairy', 'грубый /наглый',
    'to do the encore', 'повторить на бис',
    'artistry', 'мастерство /художественность',
    'moulder', 'разлагаться /разлагать',
];

const getWords = () => {
    const   questions = [],
            answers = [],
            words = Array(newArr.length / 2)
                .fill('')
                .map((item) => item = { id: '', question: '', answer: ''});

    for (const [index, value] of newArr.entries()) { index % 2 !== 0 ? questions.push(value) : answers.push(value) };
    
    for(const[index, word] of words.entries()) {
        word.id = id + index;
        word.question = questions[index];
        word.answer = answers[index];
    };
        
    console.log(JSON.stringify(words)); 
};

clickBtn.addEventListener('click', function(){
    getWords();
})
